### ISSUE TITLE
Problem with API

### ISSUE THREAD

**Issue by gertperdZA** [mumblebaj/MMM-Rugby#18]
Hi Mumblebaj,

I have noticed that you updated the repo recently, but there seems to be an error:

**_[ERROR] MMM-Rugby Error fetching API SPORT Ranking Data:  TypeError: Cannot read properties of undefined (reading 'slice')
    at Class.getapiSportsRankingData_**

**Comment by mumblebaj** [comment]
Hi. Please share your config.

**Comment by gertperdZA** [comment]
{
      module: 'MMM-Rugby',
      position: 'bottom_right',
      hiddenOnStartup: true,
      config: {
        rankingLimit: 5,
        matchesLimit: 5,
        matchesOlderThan: 7,
        hiddenOnStartUp: true
      }
    },

**Comment by gertperdZA** [comment]
I have left this out :  
_collectionType: "free" // api-key required_
Seems to be working with this now :)

**Comment by mumblebaj** [comment]
Awesome that it works now. Which league are you following?

**Comment by gertperdZA** [comment]
I actually only want to following international games , curriecup and URC. Any idea how I can figure the module to only show those? And with the international rankings.

**Comment by mumblebaj** [comment]
Currie Cup is on apiSport and does not have a current season available. The last currie cup on apiSport was 2018. Seems like they not sharing data. You can get URC on apiSport with league 76 but you don't have the the International rankings available from apiSport.
